// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/pizza.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderPizzaRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PizzaType        string                 `protobuf:"bytes,1,opt,name=pizza_type,json=pizzaType,proto3" json:"pizza_type,omitempty"`
	Quantity         int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreditCardNumber string                 `protobuf:"bytes,3,opt,name=credit_card_number,json=creditCardNumber,proto3" json:"credit_card_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderPizzaRequest) Reset() {
	*x = OrderPizzaRequest{}
	mi := &file_proto_pizza_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPizzaRequest) ProtoMessage() {}

func (x *OrderPizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPizzaRequest.ProtoReflect.Descriptor instead.
func (*OrderPizzaRequest) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPizzaRequest) GetPizzaType() string {
	if x != nil {
		return x.PizzaType
	}
	return ""
}

func (x *OrderPizzaRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderPizzaRequest) GetCreditCardNumber() string {
	if x != nil {
		return x.CreditCardNumber
	}
	return ""
}

type OrderPizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPizzaResponse) Reset() {
	*x = OrderPizzaResponse{}
	mi := &file_proto_pizza_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPizzaResponse) ProtoMessage() {}

func (x *OrderPizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPizzaResponse.ProtoReflect.Descriptor instead.
func (*OrderPizzaResponse) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPizzaResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPizzaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProcessPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CreditCardNumber string                 `protobuf:"bytes,1,opt,name=credit_card_number,json=creditCardNumber,proto3" json:"credit_card_number,omitempty"`
	Amount           int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_proto_pizza_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPaymentRequest) GetCreditCardNumber() string {
	if x != nil {
		return x.CreditCardNumber
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_proto_pizza_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type BakePizzaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PizzaType     string                 `protobuf:"bytes,1,opt,name=pizza_type,json=pizzaType,proto3" json:"pizza_type,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BakePizzaRequest) Reset() {
	*x = BakePizzaRequest{}
	mi := &file_proto_pizza_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BakePizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakePizzaRequest) ProtoMessage() {}

func (x *BakePizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakePizzaRequest.ProtoReflect.Descriptor instead.
func (*BakePizzaRequest) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{4}
}

func (x *BakePizzaRequest) GetPizzaType() string {
	if x != nil {
		return x.PizzaType
	}
	return ""
}

func (x *BakePizzaRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BakePizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BakePizzaResponse) Reset() {
	*x = BakePizzaResponse{}
	mi := &file_proto_pizza_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BakePizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakePizzaResponse) ProtoMessage() {}

func (x *BakePizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pizza_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakePizzaResponse.ProtoReflect.Descriptor instead.
func (*BakePizzaResponse) Descriptor() ([]byte, []int) {
	return file_proto_pizza_proto_rawDescGZIP(), []int{5}
}

func (x *BakePizzaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_pizza_proto protoreflect.FileDescriptor

const file_proto_pizza_proto_rawDesc = "" +
	"\n" +
	"\x11proto/pizza.proto\x12\x05proto\"|\n" +
	"\x11OrderPizzaRequest\x12\x1d\n" +
	"\n" +
	"pizza_type\x18\x01 \x01(\tR\tpizzaType\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12,\n" +
	"\x12credit_card_number\x18\x03 \x01(\tR\x10creditCardNumber\"G\n" +
	"\x12OrderPizzaResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"]\n" +
	"\x15ProcessPaymentRequest\x12,\n" +
	"\x12credit_card_number\x18\x01 \x01(\tR\x10creditCardNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"Y\n" +
	"\x16ProcessPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"M\n" +
	"\x10BakePizzaRequest\x12\x1d\n" +
	"\n" +
	"pizza_type\x18\x01 \x01(\tR\tpizzaType\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"-\n" +
	"\x11BakePizzaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB#Z!github.com/dynoinc/starflow/protob\x06proto3"

var (
	file_proto_pizza_proto_rawDescOnce sync.Once
	file_proto_pizza_proto_rawDescData []byte
)

func file_proto_pizza_proto_rawDescGZIP() []byte {
	file_proto_pizza_proto_rawDescOnce.Do(func() {
		file_proto_pizza_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pizza_proto_rawDesc), len(file_proto_pizza_proto_rawDesc)))
	})
	return file_proto_pizza_proto_rawDescData
}

var file_proto_pizza_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pizza_proto_goTypes = []any{
	(*OrderPizzaRequest)(nil),      // 0: proto.OrderPizzaRequest
	(*OrderPizzaResponse)(nil),     // 1: proto.OrderPizzaResponse
	(*ProcessPaymentRequest)(nil),  // 2: proto.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 3: proto.ProcessPaymentResponse
	(*BakePizzaRequest)(nil),       // 4: proto.BakePizzaRequest
	(*BakePizzaResponse)(nil),      // 5: proto.BakePizzaResponse
}
var file_proto_pizza_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pizza_proto_init() }
func file_proto_pizza_proto_init() {
	if File_proto_pizza_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pizza_proto_rawDesc), len(file_proto_pizza_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pizza_proto_goTypes,
		DependencyIndexes: file_proto_pizza_proto_depIdxs,
		MessageInfos:      file_proto_pizza_proto_msgTypes,
	}.Build()
	File_proto_pizza_proto = out.File
	file_proto_pizza_proto_goTypes = nil
	file_proto_pizza_proto_depIdxs = nil
}
